--Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
prob2 = sum [fibonacci n | n <- ns, fibonacci n `mod` 2 == 0]
    where ns = takeWhile (\n -> fibonacci n < 4000000) [1..]

fibonacci :: Int -> Int
fibonacci 1 = 1
fibonacci 2 = 2
fibonacci n = fibonacci(n - 1) + fibonacci (n - 2)